# Generated by Django 5.2 on 2025-05-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_at',
            new_name='created_at',
        ),
    ]
