# Generated by Django 5.1.6 on 2025-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_level_speciality'),
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_resources',
            field=models.ManyToManyField(blank=True, related_name='added_by_users', to='courses.resource'),
        ),
    ]
