# Generated by Django 5.1.6 on 2025-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_followed_at_follow_created_at'),
        ('users', '0003_user_added_resources'),
    ]

    operations = [
    ]
