# Generated by Django 5.2 on 2025-05-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250501_1629'),
        ('users', '0004_merge_20250501_1713'),
    ]

    operations = [
    ]
