# Generated by Django 5.1.6 on 2025-05-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250501_1629'),
        ('users', '0004_merge_20250501_1713'),
    ]

    operations = [
    ]
