# Generated by Django 5.2 on 2025-05-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250503_2248'),
        ('users', '0005_merge_20250505_2246'),
    ]

    operations = [
    ]
