# Generated by Django 5.1.6 on 2025-04-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_resource_accessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('cours-pdf', 'cours-pdf'), ('cours-video', 'cours-video'), ('td-pdf', 'td-pdf'), ('td-video', 'td-video'), ('tp-pdf', 'tp-pdf'), ('tp-video', 'tp-video')], max_length=20),
        ),
    ]
