# Generated by Django 5.2 on 2025-04-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.speciality'),
        ),
    ]
