# Generated by Django 5.1.6 on 2025-04-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('courses', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancetracking',
            name='strong_modules',
            field=models.ManyToManyField(related_name='strong_in', to='courses.module'),
        ),
        migrations.AddField(
            model_name='performancetracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trackings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancetracking',
            name='weak_modules',
            field=models.ManyToManyField(related_name='weak_in', to='courses.module'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='recommended_modules',
            field=models.ManyToManyField(to='courses.module'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
