# Generated by Django 5.1.6 on 2025-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        ('courses', '0004_level_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrecommendation',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='goals_per_day',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='recommended_chapters',
            field=models.ManyToManyField(blank=True, to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='programrecommendation',
            name='recommended_modules',
            field=models.ManyToManyField(blank=True, to='courses.module'),
        ),
    ]
