# Generated by Django 5.1.6 on 2025-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_programrecommendation_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrecommendation',
            name='recommendation_text',
            field=models.TextField(blank=True),
        ),
    ]
