# Generated by Django 5.1.6 on 2025-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_programrecommendation_recommendation_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancetracking',
            old_name='tracked_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='performancetracking',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='performancetracking',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
