# Generated by Django 5.1.6 on 2025-05-13 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_rename_tracked_at_performancetracking_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancetracking',
            old_name='created_at',
            new_name='tracked_at',
        ),
        migrations.RemoveField(
            model_name='performancetracking',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='performancetracking',
            name='feedback',
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
