# Generated by Django 5.2 on 2025-05-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement')], default='general', max_length=20),
        ),
    ]
