# Generated by Django 5.2 on 2025-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
