# Generated by Django 5.2 on 2025-05-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_announcement_level_announcement_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.announcement'),
        ),
    ]
