# Generated by Django 5.1.6 on 2025-05-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_announcement_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcement',
        ),
    ]
